First-Capstone-project
FaranoshAmini/Microverse-Conference pull request #1
Opened 2022-06-25 14:26 UTC by FaranoshAmini

In this capstone project, I build a website for Microverse by following the design guidelines including Color, Typograpghy, and Layout from the original design on Behance by [Cindy Shin](https://www.behance.net/adagio07). During this project, I designed two different pages

Home Page
About Page
I designed these two pages for both mobile and desktop users.

2022-06-25 22:57 UTC, gtekle requested changes
Hi @FaranoshAmini :wave: , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't fulfill the following:

- [ ] You should fix the failing linters before submitting you pull request for review.
![image](https://user-images.githubusercontent.com/44057863/175792615-3cd26f47-5973-46a4-aa9a-85deb08b4bdf.png)

- [ ] Only one `linters.yml` file is enough for the Github Actions workflow. would you please elaborate when two are needed in your case?
![image](https://user-images.githubusercontent.com/44057863/175792663-6362458d-cc4e-4fca-8837-e14dabf7804d.png)

- [ ] You should have a professional ReadMe for every project you do. It is also suggested to use this [ReadMe template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided by Microverse.
![image](https://user-images.githubusercontent.com/44057863/175792629-2c44078f-651f-4258-9ea1-83eab70c554a.png)

- [ ] I couldn't find video presentation of the project. Since it part of the project requirement, kindly add that as well.
![image](https://user-images.githubusercontent.com/44057863/175792710-9734f4d5-5819-4071-b29f-364472bcf415.png)

- [ ] Kindly use a descriptive pull request summary and pull request title
![image](https://user-images.githubusercontent.com/44057863/175792753-5fb04f92-d2ce-47c4-9f6f-1733b2b9d553.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-06-28 09:06 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @FaranoshAmini, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Professional Readme
✔️ All linters passing
✔️ Good job so far

## Required 
- Video presentation:
- [ ] Kindly highlight a piece of the code the student finds interesting or is proud of making in the video.
- [ ] Make sure your face is visible while recording the video presentation as it's a requirement.

- Capstone
- [ ] Kindly view [this](https://www.loom.com/share/309d61341a2b4b3798c2f7fc4dd92e4b) loom video to make changes.
- [ ] Kindly make sure to follow the spacing, width, height, and font size as suggested in the loom video.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 09:06 UTC, sja-thedude commented on README.md
> +-[LIVE DEMO](https://faranoshamini.github.io/First-Capstone-Project/)
- [ ] Kindly make sure to deploy your website correctly, currently, this link is not displaying anything.

2022-06-28 09:06 UTC, sja-thedude commented on README.md
> +- Special Thanks [Cindy Shin](https://www.behance.net/adagio07)
- [ ] Kindly repharse this as "I would like to give credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the Creative Commons License."

2022-06-28 09:06 UTC, sja-thedude commented on about.html
> +        <div class="sub-title">What Makes Microverse Different?</div>
- [ ] Kindly wrap the heading in h1 tags.

2022-06-28 09:06 UTC, sja-thedude commented on script.js
> +
- [ ] Kindly make sure to add 2 more speakers as suggested in the attached loom video. 
- [ ] Kindly make sure to add background checks image to all the images as suggested in the attached loom video. 
- [ ] Kindly make sure to add more button for the mobile version as suggested in the attached loom video.

2022-06-28 09:06 UTC, sja-thedude commented on index.html
> +                </div>
- [ ] Kindly make sure to add 2 more cards as suggested in the attached loom video. 
- [ ] Kindly make sure to follow the spacing as suggested in the attached loom video.

2022-06-28 09:06 UTC, sja-thedude commented on about.html
> +                class="menu" id="openAbout">About</a></li>
- [ ] Kindly make sure to replace about with home as suggested in the loom video.

2022-06-29 15:26 UTC, omarsalem7 approved these changes
Hi @FaranoshAmini 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ No linter errors. 
✅ Descriptive pull request 
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 15:34 UTC, FaranoshAmini commented
@omarsalem7 Thank you so much for your kind review and feedback.

2022-06-29 15:45 UTC, merged